item/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.show_home),
    path('details/<gid>', views.show_details),
    path('submit/', views.show_submit),
    path('favorite/', views.show_favorite),
    path('click_favorite/', views.change_favorite),
    path('cancel_favorite/', views.cancel_favorite),
    path('isfavorite/', views.isfavorite),
    path('edit_details/<gid>', views.edit_details, name='edit_details'),
    path('delete/<gid>', views.gdelete, name='delete'),
]

second_hand_websites/urls.py
from django.contrib import admin
from django.urls import path, include

import item.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("item/", include('item.urls')),
    path("",include('item.urls')),
    path("user/", include('user.urls')),
]

user/urls.py
from django.urls import path
from user.views import login, home, register

urlpatterns = [
    path('login/', login.login, name="login"),
    path('image/code/', login.image_code,name='image_code'),
    path('edit_info/', home.edit_info,name="edit_info"),
    path('sms/code/', login.send_sms,name="send_sms"),
    path('login/sms/', login.login_sms,name="login_sms"),
    path('home/', home.home,name="home"),
    path('register/',register.register,name="register"),
    path('image/code/',login.image_code,name='image_code'),
    path('on_sales/',home.on_sales,name="on_sales"),
    path('logout/',home.logout,name="logout"),
    path('edit_pwd/',home.edit_pwd,name='edit_pwd')
]

user/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=32)
    profile_img=models.CharField(verbose_name='头像', max_length=100)


class UserFavorite(models.Model):
    userid = models.IntegerField(verbose_name="用户id")
    itemid = models.IntegerField(verbose_name="商品id")

user/forms/edit_info.py
from django import forms
from django.core.validators import RegexValidator
from hashlib import md5
from jsonschema.exceptions import ValidationError

from user import models
from user.forms.bootstrap import BootStrap


class InfoForm(BootStrap, forms.Form):
    username = forms.CharField(
        label='用户名',
        widget=forms.TextInput(),
        required=True,
    )
    mobile_phone = forms.CharField(
        label='手机号',
        widget=forms.TextInput,
        required=True,
    )
    email = forms.CharField(
        label='邮箱',
        widget=forms.TextInput(),
        required=True,
    )

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

user/forms/edit_pwd.py
from django import forms
from django.core.validators import RegexValidator
from hashlib import md5
from jsonschema.exceptions import ValidationError

from user import models
from user.forms.bootstrap import BootStrap


class PwdForm(BootStrap, forms.Form):
    old_pwd=forms.CharField(
        label='旧密码',
        widget=forms.PasswordInput(render_value=True),
        required=True)
    new_pwd = forms.CharField(
        label='新密码',
        widget=forms.PasswordInput(render_value=True),
        required=True)


    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

user/forms/login_form.py
from django import forms
from django.core.validators import RegexValidator
from hashlib import md5
from jsonschema.exceptions import ValidationError

from user import models
from user.forms.bootstrap import BootStrap


class LoginForm(BootStrap, forms.Form):
    mobile_phone = forms.CharField(
        label='手机号',
        widget=forms.TextInput(),
        required=True,
        validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号格式不正确'), ]
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(render_value=True),
        required=True
    )
    code = forms.CharField(label='图⽚验证码')
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    # def clean_password(self):
    #     pw = self.cleaned_data.get('password')
    #     return md5(pw.encode()).hexdigest()

    def clean_code(self):
        """ 钩⼦ 图⽚验证码是否正确？ """
        # 读取⽤户输⼊的验证码
        code = self.cleaned_data['code']
        # 去session获取⾃⼰的验证码
        session_code = self.request.session.get('image_code')
        if not session_code:
            raise ValidationError('验证码已过期，请重新获取')
        if code.strip().upper() != session_code.strip().upper():
            raise ValidationError('验证码输⼊错误')
        return code

user/forms/login_sms_form.py
from django import forms
from django.conf import settings
from django.core.validators import RegexValidator
from django.http import HttpResponse
from jsonschema.exceptions import ValidationError

from user import models
from utils.tencent.sms import send_sms_single
import random
from user.forms.bootstrap import BootStrap


class LoginSmsForm(BootStrap, forms.Form):
    mobile_phone = forms.CharField(
        label='手机号',
        validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号格式不正确'), ]
    )
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput())

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    #     未进行检验
    # def clean_mobile_phone(self):
    #     mobile_phone = self.cleaned_data['mobile_phone']
    #     exists = models.UserInfo.objects.filter(mobile_phone=mobile_phone).exists()
    #
    #     if not exists:
    #         raise ValidationError('⼿机号不存在')
    #     return mobile_phone
    # #
    def clean_code(self):
        code = self.cleaned_data['code']
        print(code)
        mobile_phone = self.cleaned_data.get('mobile_phone')
        # ⼿机号不存在，则验证码⽆需再校验
        if not mobile_phone:
            return code
        session_code = self.request.session.get('code')  # 从session中获取验证码
        if not session_code:
            raise ValidationError('验证码失效或未发送，请重新发送')
        # redis_str_code = redis_code.decode('utf-8')
        if code.strip().upper() != session_code.strip().upper():
            raise ValidationError('验证码错误，请重新输⼊')
        return code

user/forms/register_form.py
from django import forms
from user import models
from user.forms.bootstrap import BootStrap
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

class RegisterForm(BootStrap,forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ['username', 'email', 'password', 'confirm_password', 'mobile_phone', 'code']


    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request


# 手机号
    mobile_phone = forms.CharField(
        label='手机号',
        validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号格式不正确'), ]
)
    # email = forms.CharField(
    #     label='邮箱',
    #     validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '邮箱格式不正确'), ]
    # )

    password = forms.CharField(
        label='密码',
    # widget=forms.PasswordInput(attrs={'class': 'form-control'})
        widget=forms.PasswordInput(),
        min_length=6,
        max_length=20,
        error_messages={
            'min_length': "密码不能小于6个字符",
            'max_length': "密码不能大于20个字符"

    }
)

    confirm_password = forms.CharField(
        label='确认密码',
        widget=forms.PasswordInput(),
        min_length=6,
        max_length=20,
        error_messages={
            'min_length': "重复密码⻓度不能⼩于6个字符",
            'max_length': "重复密码⻓度不能⼤于20个字符"
    },
)

    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput()
)
    def clean_username(self):
        username = self.cleaned_data['username']
        exists = models.UserInfo.objects.filter(username=username).exists()
        if exists:
            raise ValidationError('⽤户名已存在')
            # self.add_error('username','⽤户名已存在')
        return username
    def clean_email(self):
        username = self.cleaned_data['email']
        exists = models.UserInfo.objects.filter(username=username).exists()
        if exists:
            raise ValidationError('邮箱已存在')
            # self.add_error('username','⽤户名已存在')
        return username

    def clean_password(self):
        pwd = self.cleaned_data['password']
        return pwd

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get('password')
        confirm_pwd = self.cleaned_data['confirm_password']
        if pwd != confirm_pwd:
            raise ValidationError('两次密码不⼀致')
        return confirm_pwd
    def clean_mobile_phone(self):
        mobile_phone = self.cleaned_data['mobile_phone']
        exists = models.UserInfo.objects.filter(mobile_phone=mobile_phone).exists()
        if exists:
            raise ValidationError('电话已存在')
        return mobile_phone
    def clean_code(self):
        code = self.cleaned_data['code']
        mobile_phone = self.cleaned_data.get('mobile_phone')
        if not mobile_phone :
            return code
        redis_code = self.request.session.get('code')  # 从session中获取验 证码
        if not redis_code:
            raise ValidationError('验证码失效或未发送，请重新发送')
        # redis_str_code = redis_code.decode('utf-8')
        # if code.strip() != redis_code:
        if code != redis_code:
            raise ValidationError('验证码错误，请重新输⼊')
        return code

user/views/home.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect

from user.forms.edit_info import InfoForm
from user.forms.edit_pwd import PwdForm
from user.models import UserInfo
from item.models import Items
import os

def home(request):
    info = request.session.get('info')
    user_id = info['id']
    query_set = UserInfo.objects.filter(id=user_id).first()
    on_sales_num = Items.objects.filter(userid=user_id).count()

    return render(request, 'user/home.html', {'user_info': query_set, 'on_sales_num': on_sales_num})


def on_sales(request):
    info = request.session.get('info')
    user_id = info['id']
    query_set = UserInfo.objects.filter(id=user_id).first()
    on_sales = Items.objects.filter(userid=user_id)

    return render(request, 'user/on_sales.html', {'user_info': query_set, 'on_sales': on_sales})


def logout(request):
    request.session.flush()
    return redirect('/item/')

def edit_info(request):
    info = request.session.get('info')
    user_id = info['id']
    query_set = UserInfo.objects.filter(id=user_id).first()
    if request.method == 'GET':
        user_info = UserInfo.objects.filter(id=user_id).values_list('username', 'email', 'mobile_phone','profile_img').first()
        init_info = {'username': user_info[0], 'mobile_phone': user_info[2], 'email': user_info[1]}
        form = InfoForm(request, initial=init_info)
        return render(request, 'user/edit_info.html', {'user_info': query_set, 'form': form})

    form = InfoForm(request, data=request.POST)
    user = UserInfo.objects.filter(id=user_id).first()
    if form.is_valid():
        file = request.FILES.get('file')
        if file:
            newimg = file.name
            user.profile_img=newimg
            with open(os.path.join('static/profile_img', file.name), 'wb') as f:  # 在static目录下创建同名文件
                for line in file.chunks():
                    f.write(line)
        new_name = form.cleaned_data['username']
        new_phone = form.cleaned_data['mobile_phone']
        new_email = form.cleaned_data['email']
        user.username = new_name
        user.mobile_phone = new_phone
        user.email = new_email
        user.save()
        print('info_saved!')
        return redirect('/user/home/')


def edit_pwd(request):
    info = request.session.get('info')
    user_id = info['id']
    print(user_id)
    query_set = UserInfo.objects.filter(id=user_id).first()
    print(query_set)
    if request.method == 'GET':
        user_info = UserInfo.objects.filter(id=user_id).values_list('username', 'email', 'mobile_phone').first()

        form = PwdForm(request)
        return render(request, 'user/edit_pwd.html', {'form': form,'user_info':query_set})

    form = PwdForm(request, data=request.POST)
    user = UserInfo.objects.filter(id=user_id).first()
    if form.is_valid():
        old_pwd = form.cleaned_data['old_pwd']
        new_pwd = form.cleaned_data['new_pwd']
        if old_pwd==user.password:
            if old_pwd==new_pwd:
                form.add_error('new_pwd', '新密码不能与旧密码相同')
                return render(request, 'user/edit_pwd.html', {'form': form})
            user.password=new_pwd
            return redirect('/user/home/')
        else:
            form.add_error('old_pwd', '旧密码错误')
            return render(request, 'user/edit_pwd.html', {'form': form})

user/views/login.py
from io import BytesIO

from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect
from jsonschema.exceptions import ValidationError
from user.forms.login_form import LoginForm
from user import models
from user.forms.login_sms_form import LoginSmsForm
from user.forms.register_form import RegisterForm
from user.forms.send_sms_form import SendSmsForm
from user.models import UserInfo
from utils.image_code import check_code


def login(request):
    if request.method == 'GET':
        form = LoginForm(request)
        return render(request, 'user/login.html', {'form': form})
    form = LoginForm(request, data=request.POST)
    try:
        if form.is_valid():
            phone_number = form.cleaned_data['mobile_phone']
            password = form.cleaned_data['password']
            user = UserInfo.objects.get(mobile_phone=phone_number)
            if user.password == password:
                # 登录成功，将用户标识存储在session中
                request.session["info"] = {'id': user.id, 'name': user.username}
                request.session.set_expiry(60 * 60 * 24 * 14)
                return redirect('/item/')  # 重定向到登录成功后的页面
            else:
                form.add_error('password', '密码错误!')
    except ValidationError as e:
        form.add_error('code', e)
    return render(request, 'user/login.html', {'form': form})


def send_sms(request):
    form = SendSmsForm(request, data=request.GET)
    if form.is_valid():
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


def login_sms(request):
    if request.method == 'GET':
        form = LoginSmsForm(request)

        return render(request, 'user/login_sms.html',{'form':form})

    form = LoginSmsForm(request, data=request.POST)
    try:
        if form.is_valid():
            mobile_phone = form.cleaned_data['mobile_phone']
            user_object = models.UserInfo.objects.filter(mobile_phone=mobile_phone).first()
            if user_object:
                request.session['id'] = user_object.id
                request.session['username'] = user_object.username
                request.session.set_expiry(60 * 60 * 24 * 14)
                return redirect('/item/')
            form.add_error('mobile_phone', '手机号或验证码错误')
    except ValidationError as e:
        form.add_error('code', e)
    return render(request, 'user/login_sms.html', {'form': form})
def image_code(request):
    # 生成图片验证码
    image_object, code = check_code()
    request.session['image_code'] = code
    request.session.set_expiry(6000)  # 主动修改验证码的过期时间为60s
    # 将图⽚信息保存到内存中使⽤省去每次都去数据库查询的操作
    stream = BytesIO()
    image_object.save(stream, 'png')
    return HttpResponse(stream.getvalue())

user/views/register.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from jsonschema.exceptions import ValidationError

from user.forms.register_form import RegisterForm


def register(request):
    if request.method == 'GET':
        form = RegisterForm(request)
        return render(request, 'user/register.html', {'form': form})
    else:
        form = RegisterForm(request, data=request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/user/login/sms/')
            form.add_error('mobile_phone', '手机号或验证码错误')
        except ValidationError as e:
            form.add_error('code', e)
        return render(request, 'user/register.html', {'form': form})
    # try:
    #     if form.is_valid():
    #         mobile_phone = form.cleaned_data['mobile_phone']
    #         user_object = models.UserInfo.objects.filter(mobile_phone=mobile_phone).first()
    #         if user_object:
    #             request.session['id'] = user_object.id
    #             request.session['username'] = user_object.username
    #             request.session.set_expiry(60 * 60 * 24 * 14)
    #             return redirect('/user/index/')
    #         form.add_error('mobile_phone', '手机号或验证码错误')
    # except ValidationError as e:
    #     form.add_error('code', e)
    # return render(request, 'user/login_sms.html', {'form': form})

user/templates/user/edit_pwd.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block css %}
    <style>




    </style>
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <div class="text-center mb-3">

                    <img src="/static/profile_img/{{ user_info.profile_img }}" alt="头像" class="img-circle" style="width: 340px;height: 340px; margin-top: 50px; margin-right: 60px; ">
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="mb-0">个人信息</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" novalidate>
                        {% csrf_token %}
                            {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg" style="color: red">{{ field.errors.0 }}</span>
                            </div>
                            {% endfor %}
                            <input type="submit" value="提交" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

user/templates/user/login_sms.html
{% load static %}

<head>
   <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <title>登陆</title>
    <style>
         .account h2 {
            margin-top: 10px;
            text-align: center;
        }
        .error-msg{
            color:red;
            height:9px;
            font-size: 13px;
        }
        .glass-container{
            width: 400px;
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 20px;
            border-radius: 0;
            backdrop-filter: blur(0px);
            background-color: rgba(0,191,255, 0);
            box-shadow: rgba(0, 0, 0, 0.3) 2px 8px 8px;
            border: 0 rgba(255,255,255,0.4) solid;
            border-bottom: 0 rgba(40,40,40,0.35) solid;
            border-right: 0 rgba(40,40,40,0.35) solid;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
            color: black;
            font-size: 1.5em;
        }
        body{
            background-image: url("{% static "images/bg_login1.jpg" %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            margin: 0;
            padding: 0;
        }
        a{
            color: white;
            font-size: 0.9em;
        }
        h2{
            text-align: center;
        }
        .btn {
	        background: white;
            color: black;
            width: 8em;
        }

        .btn:hover{
            background: black;
            color: white;
        }
        a:hover{
            color: #afd9ee;
        }
    </style>
    <title></title>
</head>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> 二手交易平台 </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/item/">返回</a></li>
            </ul>
        </div>
    </div>
</nav>


<body>
<div class="glass-container" id="glass">

    <form method="post" novalidate>
    <h2>用户登录</h2>
        {% csrf_token %}
        {% for field in form %}
            {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>

                        <div class="clearfix">
                            <div class="col-md-6" style="padding-left: 0;">{{ field }}<div class="error-msg">{{ field.errors.0 }}</div></div>
                            <div class="col-md-6"><input type="button" id="btnSms" class="btn btn-default"
                                                         value="获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
            <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    <div class="error-msg">{{ field.errors.0 }}</div>
                    </div>
            {% endif %}
        {% endfor %}
<div>
        </div>
        <div style="text-align: center">
            <input id="btnSubmit" type="submit" class="btn btn-primary" value="登录"/>
        </div>
        <div style="text-align: center; font-size: 1.2em; margin-top: 1em;">
            <a href="{% url 'register' %}">注册</a>
            <a href="{% url 'login' %}">密码登陆</a>
        </div>
    </form>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    <script>
    btnSms_click()
console.log('dianji')


      function btnSms_click(){
 $('#btnSms').click(function(){
        $('.error-msg').empty();
     {#获取输入的手机号码#}
     var mobile_phone=$('#id_mobile_phone').val();
console.log(mobile_phone)
     $.ajax({
         {#请求的路由地址#}
         url:"/user/sms/code/",
         type:"GET",
         data:{
            mobile_phone:mobile_phone,
             tpl:"login",
         },
         dataType:"JSON",
         success:function(res){
             if (res.status) {
          sendSmsRemind(); }
             else {
 // 错误信息
  console.log(res.err);
                 // {status:False, error:{ mobile_phone: ["错误信 息"，],code: ["错误信息"，] } }
    $.each(res.error, function (key, value) {
    {#key：字段名#}
    $("#id_" + key).next().text(value[0]);
      }) }
         }

     })


 })
    }
function sendSmsRemind() {
 var $smsBtn = $('#btnSms');
 $smsBtn.prop('disabled', true); // 禁⽤
 var time = 60;
 var remind = setInterval(function () {
 $smsBtn.val(time + '秒重新发送');
 time = time - 1;
 if (time < 1) {
 clearInterval(remind);
 $smsBtn.val('点击获取验证码').prop('disabled', false);
 }
 }, 1000) }

    </script>

</body>
</html>

user/templates/user/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
<link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">

    <style>
       .account h2 {
            margin-top: 10px;
            text-align: center;
        }
        .error-msg{
            color:red;
            height:9px;
            font-size: 13px;
        }
        .glass-container{
            width: 400px;
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 20px;
            border-radius: 0;
            backdrop-filter: blur(0px);
            background-color: rgba(0,191,255, 0);
            box-shadow: rgba(0, 0, 0, 0.3) 2px 8px 8px;
            border: 0 rgba(255,255,255,0.4) solid;
            border-bottom: 0 rgba(40,40,40,0.35) solid;
            border-right: 0 rgba(40,40,40,0.35) solid;

            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            padding: 20px 40px;
            color: black;
            font-size: 1.5em;
        }
        body{
            background-image: url("{% static "images/bg_login1.jpg" %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            margin: 0;
            padding: 0;
        }
        a{
            color: white;
            font-size: 0.9em;
        }
        h2{
            text-align: center;
        }
        .btn {
	        background: white;
            color: black;
            width: 8em;
        }

        .btn:hover{
            background: black;
            color: white;
        }
        a:hover{
            color: #afd9ee;
        }

    </style>

</head>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> 二手交易平台 </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/item/">返回</a></li>
            </ul>
        </div>
    </div>
</nav>


<body>
<div class="glass-container" id="glass">
    <form method="post" novalidate>
     <h2>用户注册</h2>
        {% csrf_token %}
        {% for field in form %}
            {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>

                        <div class="clearfix">
                            <div class="col-md-6" style="padding-left: 0;">{{ field }}<div class="error-msg">{{ field.errors.0 }}</div></div>
                            <div class="col-md-6"><input type="button" id="btnSms" class="btn btn-default "
                                                         value="获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
            <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    <div class="error-msg">{{ field.errors.0 }}</div>
                    </div>
            {% endif %}
        {% endfor %}


        <div style="text-align: center">
            <input id="btnSubmit" type="submit" class="btn btn-primary" value="注  册"/>
        </div>
        <div style="text-align: center; font-size: 1em; margin-top: 1em;">
                <a href="{% url 'login_sms' %}">短信登录</a>
                <a href="{% url 'login' %}">密码登录</a>
        </div>
    </form>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    <script>
    btnSms_click()
    btnSubmit_click()


      function btnSms_click(){
 $('#btnSms').click(function(){
        $('.error-msg').empty();
     {#获取输入的手机号码#}
     var mobile_phone=$('#id_mobile_phone').val();
console.log(mobile_phone)
     $.ajax({
         {#请求的路由地址#}
         url:"/user/sms/code/",
         type:"GET",
         data:{
            mobile_phone:mobile_phone,
             tpl:"register",
         },
         dataType:"JSON",
         success:function(res){
             if (res.status) {
          sendSmsRemind(); }
             else {
 // 错误信息
  console.log(res.err);
                 // {status:False, error:{ mobile_phone: ["错误信 息"，],code: ["错误信息"，] } }
    $.each(res.error, function (key, value) {
    {#key：字段名#}
    $("#id_" + key).next().text(value[0]);
      }) }
         }

     })


 })
    }
function sendSmsRemind() {
 var $smsBtn = $('#btnSms');
 $smsBtn.prop('disabled', true); // 禁⽤
 var time = 60;
 var remind = setInterval(function () {
 $smsBtn.val(time + '秒重新发送');
 time = time - 1;
 if (time < 1) {
 clearInterval(remind);
 $smsBtn.val('点击获取验证码').prop('disabled', false);
 }
 }, 1000) }
function btnSubmit_click() {
 $('#btnSubmit').click(function () {
 // 每次提交的时候如果先清空错误信息
     console.log('?')
 $('.error-msg').empty();
 // 收集表单中的数据（找到每⼀个字段）$('#regForm').serialize()
 // 数据ajax发送到后台
 $.ajax({
 url: "/user/register/",
 type: "POST",
 data: $('#regForm').serialize(), // 所有字段数据 + csrf token
 dataType: "JSON",
 success: function (res)
 {
     console.log(res)
 if (res.status) {
     console.log('res.data')
 // location.href = res.data;
 } else {
 $.each(res.error, function (key, value) {
 $("#id_" + key).next().text(value[0]);
 })
 }
 }
 })
 }) }
    </script>
</body>
</html>